spring:
  application:
    name: temporal-boot
  temporal:
    namespace: default
    connection:
      target: localhost:7233
    workers:
      - name: send-email-worker
        task-queue: email_subscription
      - name: hello-worker
        task-queue: hello
    workers-auto-discovery:
      packages:
        - com.ianxc.temporalboot.temporal.activities
        - com.ianxc.temporalboot.temporal.workflows

app:
  schedules:
    hello:
      - name: "fbb7349b-66b5-483c-a9a8-697cdbbb8123"
        cron: "7 4,10,16,22 * * *"
